services:
  kinopoisk-api:
      image: kinopoisk-api
      ports:
        - "8080:8080"
  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus
    env_file:
      - .env
volumes:
  prometheus-data:
#  grafana:
#    image: grafana/grafana-oss:10.0.3
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana-data:/var/lib/grafana