version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"  # Экспонируем порт 9090 для Prometheus
    volumes:
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Конфигурация Prometheus
    networks:
      - monitoring_network
    depends_on:
      - kinopoisk-api  # Prometheus зависит от API

  kinopoisk-api:
    build:
      context: .  # Используем Dockerfile из текущей директории для сборки приложения
    ports:
      - "8080:8080"  # Экспонируем порт 8080 для вашего бэкенда
    networks:
      - monitoring_network
    env_file:
      - .env

# Глобальное определение сети
networks:
  monitoring_network: