global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'kinopoisk-api'
    static_configs:
      - targets: [ 'kinopoisk-api:2020' ]