name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Используйте самохостинговый агент

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push
      - name: Stop and remove old containers
        run: |
          docker-compose down
          docker-compose up -d